#!/usr/bin/env bash
# Detect the host's GPU situation and emit `.deploy.env` for the
# deploy script. Idempotent — re-run any time the hardware changes.
#
# Output (sourced by scripts/deploy.sh):
#
#   DEPLOY_MODE          gpu|cpu
#   GPU_COUNT            integer
#   GPU_NAME             string (first GPU's model name)
#   GPU_MEMORY_MB        integer (first GPU's total VRAM)
#   NVIDIA_RUNTIME_OK    1|0 (whether docker has the nvidia runtime)
#   VLM_ENGINE           vllm-engine|mlx-engine|transformers
#
# Env overrides (take precedence over autodetect):
#   DEPLOY_MODE=cpu|gpu
#   NVIDIA_VISIBLE_DEVICES=0,1  (selects which GPUs)
#   VLM_ENGINE=...              (forces engine choice)

set -euo pipefail

cd "$(dirname "$0")/.."

DEPLOY_MODE="${DEPLOY_MODE:-}"
VLM_ENGINE="${VLM_ENGINE:-}"
GPU_COUNT=0
GPU_NAME=""
GPU_MEMORY_MB=0
NVIDIA_RUNTIME_OK=0

# ---- 1. nvidia-smi probe ----
if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
  GPU_COUNT=$(nvidia-smi -L | wc -l | tr -d ' ')
  GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader -i 0 | head -1 | xargs)
  GPU_MEMORY_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i 0 | head -1 | xargs)
  echo "[detect_gpu] nvidia-smi: $GPU_COUNT × $GPU_NAME (${GPU_MEMORY_MB} MB each)"
  [ -z "$DEPLOY_MODE" ] && DEPLOY_MODE=gpu
else
  echo "[detect_gpu] no nvidia-smi available"
  [ -z "$DEPLOY_MODE" ] && DEPLOY_MODE=cpu
fi

# ---- 2. macOS / Apple Silicon detection ----
if [ "$DEPLOY_MODE" = "cpu" ] && [ "$(uname -s)" = "Darwin" ] && [ "$(uname -m)" = "arm64" ]; then
  # MLX is local-process only — can't be containerized, but the host
  # can still run mineru-api with vlm-mlx natively outside Docker.
  echo "[detect_gpu] Apple Silicon detected — mlx-engine is the fastest option"
  echo "[detect_gpu]   (MLX cannot run inside Docker; use direct host mineru-api)"
fi

# ---- 3. NVIDIA Container Toolkit (docker runtime) ----
# Modern installs configured via `nvidia-ctk runtime configure --cdi.enabled`
# register GPUs through CDI instead of the legacy named runtime; docker info
# prints `cdi: nvidia.com/gpu=<n>` for each GPU. Either path counts as ready.
if command -v docker >/dev/null 2>&1; then
  docker_info=$(docker info 2>/dev/null || echo "")
  if echo "$docker_info" | grep -qiE "Runtimes:.*\bnvidia\b"; then
    NVIDIA_RUNTIME_OK=1
    echo "[detect_gpu] docker has nvidia runtime (legacy) registered ✓"
  elif echo "$docker_info" | grep -qE "cdi: nvidia\.com/gpu="; then
    NVIDIA_RUNTIME_OK=1
    echo "[detect_gpu] docker has nvidia GPU via CDI ✓"
  else
    if [ "$DEPLOY_MODE" = "gpu" ]; then
      echo "[detect_gpu] WARNING: nvidia runtime not registered with docker."
      echo "[detect_gpu]   install: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
      echo "[detect_gpu]   then: sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker"
    fi
  fi
else
  echo "[detect_gpu] WARNING: docker not on PATH"
fi

# ---- 4. VLM engine resolution ----
if [ -z "$VLM_ENGINE" ]; then
  case "$DEPLOY_MODE" in
    gpu) VLM_ENGINE=vllm-engine ;;
    cpu)
      if [ "$(uname -s)" = "Darwin" ] && [ "$(uname -m)" = "arm64" ]; then
        VLM_ENGINE=mlx-engine
      else
        VLM_ENGINE=transformers
      fi
      ;;
  esac
fi

# ---- 5. Emit env file ----
cat > .deploy.env <<EOF
# Generated by scripts/detect_gpu.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Sourced by scripts/deploy.sh. Re-run detect_gpu.sh to refresh.
DEPLOY_MODE=$DEPLOY_MODE
GPU_COUNT=$GPU_COUNT
GPU_NAME="$GPU_NAME"
GPU_MEMORY_MB=$GPU_MEMORY_MB
NVIDIA_RUNTIME_OK=$NVIDIA_RUNTIME_OK
VLM_ENGINE=$VLM_ENGINE
EOF

cat <<EOF

[detect_gpu] wrote .deploy.env:
  DEPLOY_MODE      = $DEPLOY_MODE
  GPU              = ${GPU_COUNT:-0} × ${GPU_NAME:-none} (${GPU_MEMORY_MB:-0} MB)
  VLM_ENGINE       = $VLM_ENGINE
  NVIDIA_RUNTIME   = $([ "$NVIDIA_RUNTIME_OK" = "1" ] && echo "ok" || echo "missing")

next: bash scripts/deploy.sh
EOF
